// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeyY22tFVdNs3SEDVFY_9k5uclXjTnTXw',
    appId: '1:627442102398:web:f0732974db92c76492282f',
    messagingSenderId: '627442102398',
    projectId: 'kth-mobile-app',
    authDomain: 'kth-mobile-app.firebaseapp.com',
    storageBucket: 'kth-mobile-app.appspot.com',
    measurementId: 'G-GV1C7VKYPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPN68nQKcglqhwcAIhmnDvuMiK3CsPuAM',
    appId: '1:627442102398:android:1ecb7c75c248df7192282f',
    messagingSenderId: '627442102398',
    projectId: 'kth-mobile-app',
    storageBucket: 'kth-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1TLlz9bHAiKWXhdcMGh5ECn1m509y_P0',
    appId: '1:627442102398:ios:979a3124cd2635e192282f',
    messagingSenderId: '627442102398',
    projectId: 'kth-mobile-app',
    storageBucket: 'kth-mobile-app.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1TLlz9bHAiKWXhdcMGh5ECn1m509y_P0',
    appId: '1:627442102398:ios:3e36b256dca1fc3492282f',
    messagingSenderId: '627442102398',
    projectId: 'kth-mobile-app',
    storageBucket: 'kth-mobile-app.appspot.com',
    iosBundleId: 'com.example.testApp.RunnerTests',
  );
}
